### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by lihuencarranza** [ttdduu/misc#1]
hola amor, como estas? sos mi persona favorita en el mundo. 
Quiero despertarme todos los días y encontrarme con tu cara.
amor
amor
amor

**Comment by ttdduu** [comment]
> Quiero despertarme todos los días y encontrarme con tu cara.

dejemos las medialunas de lado, y que tu rostro sea mi desayuno...

> amor

es nuestra moneda de cambio... somos dos en nuestra economía circular... 

`es un code snippet`

y hoy te menciono, @lihuencarranza, por la danza de tu nombre...
mi luz que brilla, que a veces se esconde...
mi plegaria interpela al Sol ... el que mi piel recibe... 
luz o calor, luz o color... quién decide...
